### ISSUE TITLE
Error in connection of mongo db

### ISSUE THREAD

**Issue by matheusriios** [lcnetdev/bfe#89]
**When I try to start the rectum, I get the following error:**

```
body-parser deprecated bodyParser: use individual json/urlencoded middlewares node_modules/ldpjs/index.js:22:9
body-parser deprecated undefined extended: provide extended option node_modules/body-parser/index.js:105:29
[Function: createIndexDoc]
(node:30) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
listening on 3000
/app/node_modules/mongodb/lib/utils.js:671
          throw error;
          ^

MongoNetworkError: failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  name: 'MongoNetworkError'
}]
    at Pool.<anonymous> (/app/node_modules/mongodb/lib/core/topologies/server.js:438:11)
    at Pool.emit (events.js:316:20)
    at /app/node_modules/mongodb/lib/core/connection/pool.js:562:14
    at /app/node_modules/mongodb/lib/core/connection/pool.js:995:11
    at /app/node_modules/mongodb/lib/core/connection/connect.js:32:7
    at callback (/app/node_modules/mongodb/lib/core/connection/connect.js:280:5)
    at Socket.<anonymous> (/app/node_modules/mongodb/lib/core/connection/connect.js:310:7)
    at Object.onceWrapper (events.js:423:26)
    at Socket.emit (events.js:316:20)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  name: 'MongoNetworkError'
}
[nodemon] app crashed - waiting for file changes before starting...

```

**But, my connection uri is correct. On the verso, it works very well**

**Comment by kefo** [comment]
Apologies @matheusriios - I missed this one.  I updated the recto documentation to properly reflect what is happening here.  Recto no longer uses Verso, which is part of the problem you were experiencing. It uses ldpjs, which does use Mongo. I suspect there is more I can do with the documentation so let me know.
